# Generated by Django 4.1.2 on 2022-10-08 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Passive", "Passive"),
                            ("Deleted", "Deleted"),
                            ("Archived", "Archived"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("deleted_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="jobs",
            name="deleted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobs",
            name="job_location",
            field=models.CharField(
                choices=[
                    ("Istanbul", "Istanbul"),
                    ("Ankara", "Ankara"),
                    ("Edirne", "Edirne"),
                ],
                default="Istanbul",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="jobs",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Full Time Remote", "Full Time Remote"),
                    ("Full Time Hybrid", "Full Time Hybrid"),
                    ("Full Time On Site", "Full Time On Site"),
                    ("Part Time", "Part Time"),
                    ("Internship", "Internship"),
                    ("Freelance", "Freelance"),
                    ("Temporary", "Temporary"),
                ],
                default="Full Time Remote",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="jobs",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Passive", "Passive"),
                    ("Deleted", "Deleted"),
                    ("Archived", "Archived"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="jobs_creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="jobs",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="jobs", to="job.tag"
            ),
        ),
    ]
