# Generated by Django 4.1.2 on 2022-10-08 11:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job", "0003_rename_tag_tags"),
    ]

    operations = [
        migrations.RenameModel(old_name="Jobs", new_name="Job",),
        migrations.RenameModel(old_name="Tags", new_name="Tag",),
    ]
