# Generated by Django 4.1.2 on 2022-10-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_rename_jobs_job_rename_tags_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Passive", "Passive"),
                    ("Deleted", "Deleted"),
                    ("Archived", "Archived"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
    ]
