# Generated by Django 4.1.2 on 2022-10-08 12:10

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job", "0005_alter_tag_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_search_title", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Passive", "Passive"),
                            ("Deleted", "Deleted"),
                            ("Archived", "Archived"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "searcher",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="searcher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, null=True, related_name="search_tags", to="job.tag"
                    ),
                ),
            ],
            options={"ordering": ["-created_date"],},
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_letter", ckeditor.fields.RichTextField()),
                ("resume", models.FileField(upload_to="resume/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Passive", "Passive"),
                            ("Deleted", "Deleted"),
                            ("Archived", "Archived"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("deleted_date", models.DateTimeField(blank=True, null=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Applicant",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job.job",
                        verbose_name="Job",
                    ),
                ),
            ],
            options={"ordering": ["-created_date"],},
        ),
    ]
