# Generated by Django 4.1.2 on 2022-10-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_jobsearch_jobapplication"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobsearch", name="tags",),
    ]
