# Generated by Django 4.1.2 on 2022-10-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0008_alter_jobapplication_cover_letter_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="applicant",),
    ]
