# Generated by Django 4.1.2 on 2022-10-09 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job", "0010_tag_tags_related"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="jobs", to="job.tag"),
        ),
        migrations.AlterField(
            model_name="jobsearch",
            name="searcher",
            field=models.ManyToManyField(
                blank=True, related_name="searcher", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
